# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Amrit's blog
email: ap4.singh@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Dr. Amrit is a physician-turned-data scientist. He is pursuing his MS in computer science at Georgia Tech, USA. He did his MBBS from Maulana Azad medical college(MAMC), India. He believes that the fusion of medicine and artificial intelligence is an essential path to the democratization of health. He participates in data science competitions at kaggle and currently is Kaggle 4x Expert This blog is on his journey of artificial intelligence in medicine.
baseurl: "/blogs" # the subpath of your site, e.g. /blog
url: "https://amritpal-001.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
